### PR TITLE
update to scrcpy v2.4 (debugging)

### PR DESCRIPTION
**Pull request by k23223**
1、更新到scrcpy v2.4 目前最新版(2024-03-03发布)
2、home back click 已测试

### CODE REVIEW

**Comment by leng-yue** [comment]
@aentwist Do you have any chance to test this PR? I don't have any android device currently.

**Comment by aentwist** [comment]
I don't know if it is normal but Im actually using an Android emulator on my PC, ldplayer in my case 😅 That is how my project is. Although I do have an android I am not up to speed on using it. Anyways testing using an emulator is probably fine, but I don't really have an interest in this so I won't promise anything right now.

**Comment by ActualMasterOogway** [comment]
> I don't know if it is normal but Im actually using an Android emulator on my PC, ldplayer in my case 😅 That is how my project is. Although I do have an android I am not up to speed on using it. Anyways testing using an emulator is probably fine, ~but I don't really have an interest in this~ edit: I couldnt read it, this is very interesting but I dont want to commit the time right now to figure out how to do thorogh testing. so I won't promise anything right now.

Hey, Im open up for testing only problem is I cant build the av version of your repo. Could u sync your fork for it to work?
Thanks in advance

**Comment by m-danya** [comment]
Seems to work smoothly, thanks!

**Comment by leng-yue** [comment]
Cool

**Comment by aentwist** [comment]
This commit has the test suite failing, looks like only one test. The test probably just needs updated for the new version of scrcpy, but I don't know whether anyone is up to speed enough at the moment to fix it.

```
FAILED tests/test_control.py::test_control_touch - AssertionError: assert b'\x02\x00\x1...0\x00\x00\x01' == b'\x02\x00\xf...0\x00\x00\x01'
```

**Comment by aentwist** [comment]
I think I can handle this

https://github.com/Genymobile/scrcpy/issues/673#issuecomment-516360374

https://github.com/Genymobile/scrcpy/blob/af573090741e73c66c4a543dcd94fd771c51b7be/app/tests/test_control_msg_serialize.c#L77-L114

**Comment by aentwist** [comment]
Ok got it, the test did just need updated. Next time maybe try using it... spooky otherwise :)

**Pull request merged**
